export const acsAbbreviationPatches: Record<string, string> = {
  "accounts of chemical research": "Acc. Chem. Res.",
  "acs applied materials and interfaces": "ACS Appl. Mater. Interfaces",
  "acs catalysis": "ACS Catal.",
  "acs chemical biology": "ACS Chem. Biol.",
  "acs chemical neuroscience": "ACS Chem. Neurosci.",
  "acs combinatorial science": "ACS Comb. Sci.",
  "acs energy letters": "ACS Energy Lett.",
  "acs infectious diseases": "ACS Infect. Dis.",
  "acs macro letters": "ACS Macro Lett.",
  "acs medicinal chemistry letters": "ACS Med. Chem. Lett.",
  "acs nano": "ACS Nano",
  "acs photonics": "ACS Photonics",
  "acs sustainable chemistry and engineering": "ACS Sustainable Chem. Eng.",
  "analytical chemistry": "Anal. Chem.",
  "biochemistry": "Biochemistry",
  "bioconjugate chemistry": "Bioconjugate Chem.",
  "biomacromolecules": "Biomacromolecules",
  "chemical reviews": "Chem. Rev.",
  "chemical research in toxicology": "Chem. Res. Toxicol.",
  "chemistry of materials": "Chem. Mater.",
  "crystal growth and design": "Cryst. Growth Des.",
  "energy and fuels": "Energy Fuels",
  "environmental science and technology": "Environ. Sci. Technol.",
  "industrial and engineering chemistry research": "Ind. Eng. Chem. Res.",
  "inorganic chemistry": "Inorg. Chem.",
  "journal of agricultural and food chemistry": "J. Agric. Food Chem.",
  "journal of chemical and engineering data": "J. Chem. Eng. Data",
  "journal of chemical education": "J. Chem. Educ.",
  "journal of chemical information and modeling": "J. Chem. Inf. Model.",
  "journal of chemical theory and computation": "J. Chem. Theory Comput.",
  "journal of medicinal chemistry": "J. Med. Chem.",
  "journal of natural products": "J. Nat. Prod.",
  "journal of organic chemistry": "J. Org. Chem.",
  "journal of physical chemistry a": "J. Phys. Chem. A",
  "journal of physical chemistry b": "J. Phys. Chem. B",
  "journal of physical chemistry c": "J. Phys. Chem. C",
  "journal of physical chemistry letters": "J. Phys. Chem. Lett.",
  "journal of proteome research": "J. Proteome Res.",
  "langmuir": "Langmuir",
  "macromolecules": "Macromolecules",
  "molecular pharmaceutics": "Mol. Pharmaceutics",
  "nano letters": "Nano Lett.",
  "organic letters": "Org. Lett.",
  "organic process research and development": "Org. Process Res. Dev.",
  "organometallics": "Organometallics",
  "the journal of organic chemistry": "J. Org. Chem.",
  "the journal of physical chemistry": "J. Phys. Chem.",
  "the journal of the american chemical society": "J. Am. Chem. Soc.",
  "journal of the american chemical society": "J. Am. Chem. Soc.",
  "nature chemistry": "Nat. Chem.",
  "nature materials": "Nat. Mater.",
  "nature nanotechnology": "Nat. Nanotechnol.",
  "angewandte chemie international edition": "Angew. Chem., Int. Ed.",
  "chemical communications": "Chem. Commun.",
  "chemical science": "Chem. Sci.",
  "chem": "Chem",
  "chem catalysis": "Chem Catal.",
  "green chemistry": "Green Chem.",
  "materials horizons": "Mater. Horiz.",
  "organic and biomolecular chemistry": "Org. Biomol. Chem.",
  "physical chemistry chemical physics": "Phys. Chem. Chem. Phys.",
  "polymer chemistry": "Polym. Chem.",
  "rsc advances": "RSC Adv.",
  "soft matter": "Soft Matter"
};
